#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
#ifndef GURUKIT_SWIFT_H
#define GURUKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AuthenticationServices;
@import Foundation;
@import GuruShared;
@import ObjectiveC;
@import StoreKit;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="GuruKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class GuruSharedAuthProviderType;
@class GuruSharedAuthToken;
@class GuruSharedKotlinThrowable;

SWIFT_CLASS("_TtC7GuruKit17AppleAuthProvider")
@interface AppleAuthProvider : NSObject <GuruSharedDarwinAuthProvider>
@property (nonatomic, readonly, strong) GuruSharedAuthProviderType * _Nonnull type;
- (void)loginOnSuccess:(void (^ _Nonnull)(GuruSharedAuthToken * _Nonnull))onSuccess onError:(void (^ _Nonnull)(GuruSharedKotlinThrowable * _Nonnull))onError;
- (void)logoutOnSuccess:(void (^ _Nonnull)(void))onSuccess onError:(void (^ _Nonnull)(GuruSharedKotlinThrowable * _Nonnull))onError;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class ASAuthorizationController;

SWIFT_AVAILABILITY(ios,introduced=13.0)
@interface AppleAuthProvider (SWIFT_EXTENSION(GuruKit)) <ASAuthorizationControllerPresentationContextProviding>
- (ASPresentationAnchor _Nonnull)presentationAnchorForAuthorizationController:(ASAuthorizationController * _Nonnull)controller SWIFT_WARN_UNUSED_RESULT;
@end

@class ASAuthorization;

SWIFT_AVAILABILITY(ios,introduced=13.0)
@interface AppleAuthProvider (SWIFT_EXTENSION(GuruKit)) <ASAuthorizationControllerDelegate>
- (void)authorizationController:(ASAuthorizationController * _Nonnull)controller didCompleteWithAuthorization:(ASAuthorization * _Nonnull)authorization;
- (void)authorizationController:(ASAuthorizationController * _Nonnull)controller didCompleteWithError:(NSError * _Nonnull)error;
@end

@protocol GuruSharedIBillingProviderHandler;
@class GuruSharedBillingProviderType;
@class NSString;
@class GuruSharedSkuOrderParams;
@class GuruSharedSkuQueryParams;
@class GuruSharedSkuDetails;
@class SKProductsRequest;
@class SKProductsResponse;
@class SKRequest;
@class SKPaymentQueue;
@class SKPaymentTransaction;

SWIFT_CLASS("_TtC7GuruKit20AppleBillingProvider")
@interface AppleBillingProvider : NSObject <GuruSharedDarwinBillingProvider, SKPaymentTransactionObserver, SKProductsRequestDelegate>
@property (nonatomic, strong) id <GuruSharedIBillingProviderHandler> _Nonnull handler;
@property (nonatomic, strong) GuruSharedBillingProviderType * _Nonnull type;
- (void)consumePurchaseId:(NSString * _Nonnull)id onSuccess:(void (^ _Nonnull)(void))onSuccess onError:(void (^ _Nonnull)(GuruSharedKotlinThrowable * _Nonnull))onError;
- (void)dispose;
- (void)purchaseSkuOrderParams:(GuruSharedSkuOrderParams * _Nonnull)params developerPayload:(NSString * _Nonnull)developerPayload onSuccess:(void (^ _Nonnull)(void))onSuccess onError:(void (^ _Nonnull)(GuruSharedKotlinThrowable * _Nonnull))onError;
- (void)queryAndHandleUnconsumedPurchasesOnSuccess:(void (^ _Nonnull)(void))onSuccess onError:(void (^ _Nonnull)(GuruSharedKotlinThrowable * _Nonnull))onError;
- (void)querySkuDetailsParams:(NSArray<GuruSharedSkuQueryParams *> * _Nonnull)params onSuccess:(void (^ _Nonnull)(NSArray<GuruSharedSkuDetails *> * _Nonnull))onSuccess onError:(void (^ _Nonnull)(GuruSharedKotlinThrowable * _Nonnull))onError;
- (void)productsRequest:(SKProductsRequest * _Nonnull)request didReceiveResponse:(SKProductsResponse * _Nonnull)response;
- (void)request:(SKRequest * _Nonnull)request didFailWithError:(NSError * _Nonnull)error;
- (void)paymentQueue:(SKPaymentQueue * _Nonnull)queue updatedTransactions:(NSArray<SKPaymentTransaction *> * _Nonnull)transactions;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIApplication;
@class NSURL;
@class GuruSharedLoginResp;
@protocol IUserCenterListener;

/// GuruSdk 是面向 Objective-C/Swift 的公开接口类，提供了初始化、登录、支付、事件上报等功能。
/// <ul>
///   <li>
///     注意：
///     <ol>
///       <li>
///         在使用其它功能前，需要先调用 <code>GuruSdk.applicationDidFinishLaunching</code>（或 <code>applicationOpenURL</code>）来保证内部初始化完成。
///       </li>
///       <li>
///         如果需要处理 URL 回调（如第三方登录、深链等），请在应用的 <code>openURL</code> 回调中调用 <code>GuruSdk.applicationOpenURL</code>。
///       </li>
///       <li>
///         兼容 iOS 12+；在 iOS 13+ 以及多场景中，会尝试获取正确的 keyWindow 以寻找顶层控制器。
///       </li>
///     </ol>
///   </li>
/// </ul>
SWIFT_CLASS("_TtC7GuruKit7GuruSdk")
@interface GuruSdk : NSObject
/// 在应用启动时调用，用于进行 SDK 的初始化。
/// <ul>
///   <li>
///     参数:
///     <ul>
///       <li>
///         application: <code>UIApplicationDelegate</code> 中传入的应用对象。
///       </li>
///       <li>
///         launchOptions: 启动选项（如推送信息、深链等）。
///       </li>
///     </ul>
///   </li>
///   <li>
///     返回: 固定返回 <code>true</code>，表示初始化成功。
///   </li>
///   <li>
///     注意:
///     <ul>
///       <li>
///         若 SDK 尚未初始化，会在内部自动调用 <code>ensureInitialized()</code> 进行初始化。
///       </li>
///       <li>
///         建议在 <code>AppDelegate.application(_:didFinishLaunchingWithOptions:)</code> 中调用。
///       </li>
///     </ul>
///   </li>
///   <li>
///     使用示例:
///     \code
///     func application(_ application: UIApplication,
///                      didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
///         GuruSdk.applicationDidFinishLaunching(application, launchOptions: launchOptions)
///         return true
///     }
///
///     \endcode</li>
/// </ul>
+ (BOOL)applicationDidFinishLaunching:(UIApplication * _Nonnull)application launchOptions:(NSDictionary<UIApplicationLaunchOptionsKey, id> * _Nullable)launchOptions SWIFT_WARN_UNUSED_RESULT;
/// 处理外部 URL 打开应用的情况，用于深度链接或第三方登录回调。
/// <ul>
///   <li>
///     参数:
///     <ul>
///       <li>
///         application: <code>UIApplicationDelegate</code> 中传入的应用对象。
///       </li>
///       <li>
///         url: 外部打开时传入的 URL。
///       </li>
///       <li>
///         sourceApplication: 来源应用的 Bundle ID。
///       </li>
///       <li>
///         annotation: 额外注释信息。
///       </li>
///     </ul>
///   </li>
///   <li>
///     返回: 固定返回 <code>true</code>，表示已处理。
///   </li>
///   <li>
///     注意:
///     <ul>
///       <li>
///         若 SDK 尚未初始化，会在内部自动调用 <code>ensureInitialized()</code> 进行初始化。
///       </li>
///     </ul>
///   </li>
///   <li>
///     使用示例:
///     \code
///     func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any]) -> Bool {
///         return GuruSdk.applicationOpenURL(
///             app,
///             open: url,
///             sourceApplication: options[.sourceApplication] as? String,
///             annotation: options[.annotation]
///         )
///     }
///
///     \endcode</li>
/// </ul>
+ (BOOL)applicationOpenURL:(UIApplication * _Nonnull)application open:(NSURL * _Nonnull)url sourceApplication:(NSString * _Nullable)sourceApplication annotation:(id _Nullable)annotation SWIFT_WARN_UNUSED_RESULT;
/// 获取广告标识符（IDFA），可能根据隐私策略而不同。
/// <ul>
///   <li>
///     返回: 字符串形式的广告标识符。若无权限，可能为空或返回默认值。
///   </li>
///   <li>
///     使用示例:
///     <ul>
///       <li>
///         <code>let adId = GuruSdk.getAdvertisingId()</code>
///       </li>
///     </ul>
///   </li>
/// </ul>
+ (NSString * _Nonnull)getAdvertisingId SWIFT_WARN_UNUSED_RESULT;
/// 获取设备唯一标识。通常由 KMP 层自动生成或读取。
/// <ul>
///   <li>
///     返回: 字符串形式的设备 ID。
///   </li>
///   <li>
///     使用示例:
///     <ul>
///       <li>
///         <code>let deviceId = GuruSdk.getDeviceId()</code>
///       </li>
///     </ul>
///   </li>
/// </ul>
+ (NSString * _Nonnull)getDeviceId SWIFT_WARN_UNUSED_RESULT;
/// 获取当前应用的版本号（如 <code>1.0.0</code>）。
/// <ul>
///   <li>
///     返回: 字符串形式的 App 版本。
///   </li>
///   <li>
///     使用示例:
///     <ul>
///       <li>
///         <code>let appVersion = GuruSdk.getAppVersion()</code>
///       </li>
///     </ul>
///   </li>
/// </ul>
+ (NSString * _Nonnull)getAppVersion SWIFT_WARN_UNUSED_RESULT;
/// 使用指定的第三方登录方式进行登录。
/// <ul>
///   <li>
///     参数:
///     <ul>
///       <li>
///         type: 登录方式，如苹果登录、Google、Facebook 等。
///       </li>
///       <li>
///         onSuccess: 成功回调，返回登录方式及登录响应数据。
///       </li>
///       <li>
///         onError: 失败回调，返回错误信息。
///       </li>
///     </ul>
///   </li>
///   <li>
///     注意:
///     <ul>
///       <li>
///         成功后会自动调用 <code>queryAndHandleUnconsumedPurchases()</code>。
///       </li>
///     </ul>
///   </li>
///   <li>
///     使用示例:
///     \code
///     GuruSdk.login(.google, onSuccess: { provider, resp in
///         // 处理成功逻辑
///         let openid = resp.openid //用户唯一id
///         let token = resp.token //用户登录token
///     }, onError: { error in
///         // 处理错误
///     })
///
///     \endcode</li>
/// </ul>
+ (void)login:(GuruSharedAuthProviderType * _Nonnull)type onSuccess:(void (^ _Nonnull)(GuruSharedAuthProviderType * _Nonnull, GuruSharedLoginResp * _Nonnull))onSuccess onError:(void (^ _Nonnull)(GuruSharedKotlinThrowable * _Nonnull))onError;
/// 登出当前登录用户。
/// <ul>
///   <li>
///     注意:
///     <ul>
///       <li>
///         登出后需要重新登录才能执行需要用户身份的操作。
///       </li>
///     </ul>
///   </li>
///   <li>
///     使用示例:
///     <ul>
///       <li>
///         <code>GuruSdk.logout()</code>
///       </li>
///     </ul>
///   </li>
/// </ul>
+ (void)logout;
/// 调试或诊断用，返回当前 SDK 的配置信息。
/// <ul>
///   <li>
///     返回: 以字符串形式呈现的配置信息。
///   </li>
///   <li>
///     使用示例:
///     \code
///     let configStr = GuruSdk.dumpConfig()
///     print(configStr)
///
///     \endcode</li>
/// </ul>
+ (NSString * _Nonnull)dumpConfig SWIFT_WARN_UNUSED_RESULT;
/// 查询商品信息（如订阅、内购商品等）。
/// <ul>
///   <li>
///     参数:
///     <ul>
///       <li>
///         params: 商品查询参数列表。
///       </li>
///       <li>
///         onSuccess: 成功回调，返回商品详情列表。
///       </li>
///       <li>
///         onError: 失败回调，返回错误信息。
///       </li>
///     </ul>
///   </li>
///   <li>
///     注意:
///     <ul>
///       <li>
///         请先确保用户已登录，以便正确绑定购买信息。
///       </li>
///     </ul>
///   </li>
///   <li>
///     使用示例:
///     \code
///     GuruSdk.querySkuDetails([param1, param2], onSuccess: { details in
///         // 处理商品信息
///     }, onError: { error in
///         // 错误处理
///     })
///
///     \endcode</li>
/// </ul>
+ (void)querySkuDetails:(NSArray<GuruSharedSkuQueryParams *> * _Nonnull)params onSuccess:(void (^ _Nonnull)(NSArray<GuruSharedSkuDetails *> * _Nonnull))onSuccess onError:(void (^ _Nonnull)(GuruSharedKotlinThrowable * _Nonnull))onError;
/// 购买指定商品或订阅。
/// <ul>
///   <li>
///     参数:
///     <ul>
///       <li>
///         orderParams: 订单参数。
///       </li>
///       <li>
///         onSuccess: 成功回调，返回交易成功后服务器的订单号或交易标识。
///       </li>
///       <li>
///         onError: 失败回调，返回错误信息。
///       </li>
///       <li>
///         onUserCancelled: 用户主动取消购买时的回调。
///       </li>
///     </ul>
///   </li>
///   <li>
///     注意:
///     <ul>
///       <li>
///         请确保在 iOS 环境下已配置好应用内购，且有有效的商品 ID。
///       </li>
///     </ul>
///   </li>
///   <li>
///     使用示例:
///     \code
///     GuruSdk.purchase(orderParams, onSuccess: { orderId in
///         // 购买成功逻辑
///     }, onError: { error in
///         // 错误处理
///     }, onUserCancelled: {
///         // 用户取消处理
///     })
///
///     \endcode</li>
/// </ul>
+ (void)purchase:(GuruSharedSkuOrderParams * _Nonnull)orderParams onSuccess:(void (^ _Nonnull)(NSString * _Nonnull))onSuccess onError:(void (^ _Nonnull)(GuruSharedKotlinThrowable * _Nonnull))onError onUserCancelled:(void (^ _Nonnull)(void))onUserCancelled;
/// 查询并处理未消耗的购买（如未完成的交易或订阅）。
/// <ul>
///   <li>
///     注意:
///     <ul>
///       <li>
///         建议在登录成功后立即调用，用于恢复用户已购买但未确认的内容。
///       </li>
///     </ul>
///   </li>
///   <li>
///     使用示例:
///     <ul>
///       <li>
///         <code>GuruSdk.queryAndHandleUnconsumedPurchases()</code>
///       </li>
///     </ul>
///   </li>
/// </ul>
+ (void)queryAndHandleUnconsumedPurchases;
/// 上报自定义事件，带可选的事件值与额外参数。
/// <ul>
///   <li>
///     参数:
///     <ul>
///       <li>
///         name: 事件名称。
///       </li>
///       <li>
///         value: 事件值，可空。
///       </li>
///       <li>
///         params: 额外参数，键值对形式。
///       </li>
///     </ul>
///   </li>
///   <li>
///     注意:
///     <ul>
///       <li>
///         具体事件类型、用途可在后台分析埋点数据时使用。
///       </li>
///     </ul>
///   </li>
///   <li>
///     使用示例:
///     \code
///     GuruSdk.logEvent(name: "ViewPage", value: "Home", params: ["section": "banner"])
///
///     \endcode</li>
/// </ul>
+ (void)logEventWithName:(NSString * _Nonnull)name value:(NSString * _Nullable)value params:(NSDictionary<NSString *, NSString *> * _Nullable)params;
/// 上报自定义事件，只包含事件名称。
/// <ul>
///   <li>
///     参数:
///     <ul>
///       <li>
///         name: 事件名称。
///       </li>
///     </ul>
///   </li>
///   <li>
///     使用示例:
///     <ul>
///       <li>
///         <code>GuruSdk.logEvent(name: "ButtonClicked")</code>
///       </li>
///     </ul>
///   </li>
/// </ul>
+ (void)logEventWithName:(NSString * _Nonnull)name;
/// 当应用从后台进入前台时调用，用于告知 SDK 做相应处理。
/// <ul>
///   <li>
///     使用示例:
///     \code
///     func sceneDidBecomeActive(_ scene: UIScene) {
///         GuruSdk.onAppForegrounded()
///     }
///
///     \endcode</li>
/// </ul>
+ (void)onAppForegrounded;
/// 当应用进入后台时调用，用于告知 SDK 做相应处理。
/// <ul>
///   <li>
///     使用示例:
///     \code
///     func sceneWillResignActive(_ scene: UIScene) {
///         GuruSdk.onAppBackgrounded()
///     }
///
///     \endcode</li>
/// </ul>
+ (void)onAppBackgrounded;
/// 显示用户中心的登录页面示例逻辑。
/// <ul>
///   <li>
///     参数:
///     <ul>
///       <li>
///         listener: 用户中心登录过程的回调监听。
///       </li>
///     </ul>
///   </li>
///   <li>
///     注意:
///     <ul>
///       <li>
///         需在主线程显示视图。
///       </li>
///     </ul>
///   </li>
///   <li>
///     使用示例:
///     \code
///     GuruSdk.loginByUserCenter(myListener)
///
///     \endcode</li>
/// </ul>
+ (void)loginByUserCenter:(id <IUserCenterListener> _Nonnull)listener;
/// 收起或关闭用户中心，示例中为关闭当前的用户中心页面。
/// <ul>
///   <li>
///     使用示例:
///     <ul>
///       <li>
///         <code>GuruSdk.collapseUserCenter()</code>
///       </li>
///     </ul>
///   </li>
/// </ul>
+ (void)collapseUserCenter;
/// 展开或打开用户中心，示例中根据是否已登录，显示不同的页面。
/// <ul>
///   <li>
///     使用示例:
///     <ul>
///       <li>
///         <code>GuruSdk.expandUserCenter()</code>
///       </li>
///     </ul>
///   </li>
/// </ul>
+ (void)expandUserCenter;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class LoginResult;

SWIFT_PROTOCOL("_TtP7GuruKit19IUserCenterListener_")
@protocol IUserCenterListener
/// 登录成功回调
/// \param result 登录结果
///
- (void)onLoginSuccessWithResult:(LoginResult * _Nonnull)result;
/// 登录失败回调
/// \param error 错误信息
///
- (void)onLoginFailedWithError:(NSError * _Nonnull)error;
/// 登出回调
- (void)onLogout;
@end


SWIFT_CLASS("_TtC7GuruKit11LoginResult")
@interface LoginResult : NSObject
/// 登录类型，例如 facebook、google 或 guest
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
/// 用户的 OpenID
@property (nonatomic, readonly, copy) NSString * _Nonnull openid;
/// 登录令牌
@property (nonatomic, readonly, copy) NSString * _Nonnull token;
/// 初始化方法
- (nonnull instancetype)initWithType:(NSString * _Nonnull)type openid:(NSString * _Nonnull)openid token:(NSString * _Nonnull)token OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
